import type { Trip } from './types';

// The card fields from frontend/src/static/trek.ts, in its order: treks, then day hikes,
// then cultural tours. Regions are copied as written, so they don't all match
// REGION_OPTIONS yet.
export const TRIPS: readonly Trip[] = [
  {
    id: 'ebc-trek',
    title: 'EBC Trek',
    type: 'trek',
    region: 'Khumbu Valley',
    days: 12,
    maxAltitudeM: 5545,
    difficulty: 'challenging',
    image: require('../../../assets/images/trips/ebc-trek.jpg'),
  },
  {
    id: 'manaslu-circuit',
    title: 'Manaslu Circuit Trek',
    type: 'trek',
    region: 'Manaslu Region',
    days: 13,
    maxAltitudeM: 5106,
    difficulty: 'challenging',
    image: require('../../../assets/images/trips/manaslu-circuit.jpg'),
  },
  {
    id: 'langtang-valley',
    title: 'Langtang Valley Trek',
    type: 'trek',
    region: 'Langtang Region',
    days: 7,
    maxAltitudeM: 4773,
    difficulty: 'moderate',
    image: require('../../../assets/images/trips/langtang-valley.jpg'),
  },
  {
    id: 'abc-trek',
    title: 'Annapurna Base Camp Trek',
    type: 'trek',
    region: 'Annapurna Region',
    days: 7,
    maxAltitudeM: 4130,
    difficulty: 'moderate',
    image: require('../../../assets/images/trips/abc-trek.jpg'),
  },
  {
    id: 'gokyo-valley-trek',
    title: 'Gokyo Valley Trek',
    type: 'trek',
    region: 'Khumbu Region',
    days: 11,
    maxAltitudeM: 5357,
    difficulty: 'challenging',
    image: require('../../../assets/images/trips/gokyo-valley-trek.webp'),
  },
  {
    id: 'ghorepani-poon-hill-trek',
    title: 'Ghorepani Poon Hill Trek',
    type: 'trek',
    region: 'Annapurna Region',
    days: 5,
    maxAltitudeM: 3210,
    difficulty: 'moderate',
    image: require('../../../assets/images/trips/ghorepani-poon-hill-trek.webp'),
  },
  {
    id: 'mardi-himal-trek',
    title: 'Mardi Himal Trek',
    type: 'trek',
    region: 'Annapurna Region',
    days: 5,
    maxAltitudeM: 4500,
    difficulty: 'moderate',
    image: require('../../../assets/images/trips/mardi-himal-trek.webp'),
  },
  {
    id: 'shey-phoksundo',
    title: 'Shey Phoksundo Trek',
    type: 'trek',
    region: 'Dolpo Region',
    days: 8,
    maxAltitudeM: 3660,
    difficulty: 'moderate',
    image: require('../../../assets/images/trips/shey-phoksundo.webp'),
  },
  {
    id: 'tilicho-lake-trek',
    title: 'Tilicho Lake Trek',
    type: 'trek',
    region: 'Annapurna Region',
    days: 11,
    maxAltitudeM: 4919,
    difficulty: 'challenging',
    image: require('../../../assets/images/trips/tilicho-lake-trek.webp'),
  },
  {
    id: 'nagarkot-changunarayan',
    title: 'Nagarkot to Changunarayan Hike',
    type: 'hike',
    region: 'Kathmandu Valley',
    days: 1,
    maxAltitudeM: 2175,
    difficulty: 'easy',
    image: require('../../../assets/images/trips/nagarkot-changunarayan.jpg'),
  },
  {
    id: 'dhulikhel-namobuddha',
    title: 'Dhulikhel to Namobuddha Hike',
    type: 'hike',
    region: 'Kavrepalanchok',
    days: 1,
    maxAltitudeM: 1750,
    difficulty: 'moderate',
    image: require('../../../assets/images/trips/dhulikhel-namobuddha.jpg'),
  },
  {
    id: 'godawari-phulchoki',
    title: 'Godawari to Phulchoki Hike',
    type: 'hike',
    region: 'Lalitpur',
    days: 1,
    maxAltitudeM: 2765,
    difficulty: 'moderate',
    image: require('../../../assets/images/trips/godawari-phulchoki.jpg'),
  },
  {
    id: 'lumbini-tour',
    title: 'Lumbini Tour',
    type: 'cultural',
    region: 'Lumbini, Rupandehi',
    days: 3,
    maxAltitudeM: 150,
    difficulty: 'easy',
    image: require('../../../assets/images/trips/lumbini-tour.jpg'),
  },
  {
    id: 'kathmandu-valley-heritage-tour',
    title: 'Kathmandu Valley Heritage Tour',
    type: 'cultural',
    region: 'Kathmandu Valley',
    days: 3,
    maxAltitudeM: 1400,
    difficulty: 'easy',
    image: require('../../../assets/images/trips/kathmandu-valley-heritage-tour.jpg'),
  },
  {
    id: 'bandipur-hill-town',
    title: 'Bandipur Hill Town',
    type: 'cultural',
    region: 'Tanahun District',
    days: 2,
    maxAltitudeM: 1030,
    difficulty: 'easy',
    image: require('../../../assets/images/trips/bandipur-hill-town.jpg'),
  },
];
