import { FoodMenuCategory } from '@/types/trek';

export const LANGTANG_FOOD_MENU: FoodMenuCategory[] = [
  {
    key: 'hot-drinks',
    label: 'Hot Drinks',
    servingType: 'pot',
    items: [
      {
        item: 'Black Tea',
        cup: 100,
        smallPot: 500,
        mediumPot: 600,
        bigPot: 800,
      },
      {
        item: 'Milk Tea',
        cup: 150,
        smallPot: 650,
        mediumPot: 850,
        bigPot: 1050,
      },
      {
        item: 'Black Coffee',
        cup: 150,
        smallPot: 650,
        mediumPot: 850,
        bigPot: 1050,
      },
      {
        item: 'Milk Coffee',
        cup: 200,
        smallPot: 750,
        mediumPot: 950,
        bigPot: 1150,
      },
      {
        item: 'Lemon Tea',
        cup: 120,
        smallPot: 550,
        mediumPot: 650,
        bigPot: 850,
      },
      {
        item: 'Hot Lemon',
        cup: 110,
        smallPot: 540,
        mediumPot: 640,
        bigPot: 840,
      },
      {
        item: 'Ginger Honey',
        cup: 250,
        smallPot: 800,
        mediumPot: 1050,
        bigPot: 1250,
      },
      {
        item: 'Ginger Lemon',
        cup: 150,
        smallPot: 650,
        mediumPot: 850,
        bigPot: 1050,
      },
      {
        item: 'Lemon Honey',
        cup: 250,
        smallPot: 800,
        mediumPot: 1050,
        bigPot: 1250,
      },
      {
        item: 'Ginger Lemon Honey',
        cup: 270,
        smallPot: 830,
        mediumPot: 1080,
        bigPot: 1280,
      },
      {
        item: 'Ginger Tea',
        cup: 130,
        smallPot: 560,
        mediumPot: 660,
        bigPot: 860,
      },
      {
        item: 'Hot Chocolate',
        cup: 200,
        smallPot: 750,
        mediumPot: 950,
        bigPot: 1150,
      },
      {
        item: 'Hot Milk',
        cup: 150,
        smallPot: 650,
        mediumPot: 850,
        bigPot: 1050,
      },
      {
        item: 'Hot Water',
        cup: 50,
        smallPot: 150,
        mediumPot: 250,
        bigPot: 400,
      },
      {
        item: 'Hot Orange',
        cup: 200,
        smallPot: 750,
        mediumPot: 950,
        bigPot: 1150,
      },
      {
        item: 'Hot Mango',
        cup: 200,
        smallPot: 750,
        mediumPot: 950,
        bigPot: 1150,
      },
      {
        item: 'Masala Tea',
        cup: 200,
        smallPot: 750,
        mediumPot: 950,
        bigPot: 1150,
      },
      {
        item: 'Mint Tea',
        cup: 130,
        smallPot: 560,
        mediumPot: 660,
        bigPot: 860,
      },
    ],
  },
  {
    key: 'cold-drinks',
    label: 'Cold Drinks',
    servingType: 'single',
    items: [
      { item: 'Coke / Fanta / Sprite', price: 350 },
      { item: 'Can Juice (All Flavour)', price: 350 },
      { item: 'Red Bull (Energy Drink)', price: 400 },
      { item: 'Cold Lemon / Mango / Orange / Pineapple', price: 150 },
      { item: 'Mineral Water', price: 250 },
      { item: 'Mango Frooti / Apple Frooti', price: 250 },
    ],
  },
  {
    key: 'egg',
    label: 'Egg (2 pcs)',
    servingType: 'single',
    items: [
      { item: 'Boiled Egg', price: 250 },
      { item: 'Fried Egg', price: 350 },
      { item: 'Omelette', price: 300 },
      { item: 'Cheese Omelette', price: 450 },
      { item: 'Potato Omelette', price: 400 },
      { item: 'Veg Omelette', price: 400 },
      { item: 'Tomato Omelette', price: 400 },
      { item: 'Mushroom Omelette', price: 400 },
      { item: 'Mixed Omelette', price: 550 },
      { item: 'Scrambled Egg', price: 500 },
    ],
  },
  {
    key: 'pancakes',
    label: 'Pancakes',
    servingType: 'single',
    items: [
      { item: 'Plain Pancakes', price: 500 },
      { item: 'Pancake with Jam / Honey / Peanut Butter', price: 600 },
      { item: 'Apple Pancake', price: 600 },
      { item: 'Chocolate Pancake', price: 600 },
    ],
  },
  {
    key: 'bread-chapatti',
    label: 'Bread & Chapatti',
    servingType: 'single',
    items: [
      { item: 'Plain Fry Tibetan Bread', price: 450 },
      { item: 'Tingmo (Steam Bread) with Veg Curry', price: 700 },
      { item: 'Bread with Jam, Peanut, Butter and Honey', price: 600 },
      { item: 'Bread with Yak Cheese', price: 750 },
      { item: 'Plain Chapatti', price: 200 },
      { item: 'Plain Chapatti with Jam, Peanut, Butter and Honey', price: 500 },
    ],
  },
  {
    key: 'tsampa-porridge',
    label: 'Tsampa Porridge',
    servingType: 'single',
    items: [
      { item: 'Plain Tsampa Porridge', price: 400 },
      { item: 'Tsampa Porridge with Honey', price: 450 },
      { item: 'Tsampa Porridge with Muesli', price: 450 },
      { item: 'Tsampa Porridge with Apple', price: 500 },
      { item: 'Tsampa Porridge with Apple / Honey / Muesli', price: 700 },
      { item: 'Tsampa Porridge with Apple / Honey', price: 550 },
      { item: 'Tsampa Porridge with Apple / Muesli', price: 550 },
      { item: 'Tsampa Porridge with Muesli / Honey', price: 550 },
    ],
  },
  {
    key: 'oat-porridge',
    label: 'Oat Porridge',
    servingType: 'single',
    items: [
      { item: 'Porridge', price: 400 },
      { item: 'Porridge with Honey', price: 550 },
      { item: 'Porridge with Muesli', price: 500 },
      { item: 'Porridge with Apple', price: 550 },
      { item: 'Porridge with Honey / Muesli / Apple', price: 700 },
      { item: 'Porridge with Muesli / Honey', price: 550 },
      { item: 'Porridge with Muesli / Apple', price: 600 },
      { item: 'Porridge with Apple / Honey', price: 650 },
    ],
  },
  {
    key: 'noodles-soup',
    label: 'Noodles Soup',
    servingType: 'single',
    items: [
      { item: 'Plain Noodles Soup', price: 400 },
      { item: 'Veg Noodles Soup', price: 450 },
      { item: 'Egg Noodles Soup', price: 500 },
      { item: 'Mushroom Noodles Soup', price: 480 },
      { item: 'Tomato Noodles Soup', price: 450 },
      { item: 'Egg Cheese Noodles Soup', price: 600 },
      { item: 'Veg Egg Noodles Soup', price: 550 },
      { item: 'Veg Cheese Noodles Soup', price: 550 },
      { item: 'Mixed Noodles Soup', price: 700 },
      { item: 'Thenthuk Soup', price: 600 },
    ],
  },
  {
    key: 'soup',
    label: 'Soup',
    servingType: 'single',
    items: [
      { item: 'Pumpkin Soup', price: 400 },
      { item: 'Egg Soup', price: 450 },
      { item: 'Potato Soup', price: 430 },
      { item: 'Onion Soup', price: 400 },
      { item: 'Garlic Soup', price: 400 },
      { item: 'Veg Soup', price: 500 },
      { item: 'Mushroom Soup', price: 400 },
      { item: 'Tomato Soup', price: 400 },
      { item: 'Chicken Soup', price: 500 },
    ],
  },
  {
    key: 'thukpa',
    label: 'Thukpa',
    servingType: 'single',
    items: [
      { item: 'Plain Thukpa', price: 400 },
      { item: 'Veg Thukpa', price: 450 },
      { item: 'Egg Thukpa', price: 500 },
      { item: 'Veg Egg Thukpa', price: 550 },
      { item: 'Veg Cheese Thukpa', price: 600 },
      { item: 'Veg Egg Cheese Thukpa', price: 650 },
      { item: 'Veg Mushroom Thukpa', price: 550 },
      { item: 'Mushroom Thukpa', price: 500 },
      { item: 'Veg Egg Mushroom Thukpa', price: 650 },
      { item: 'Mushroom Egg Thukpa', price: 600 },
      { item: 'Mushroom Cheese Thukpa', price: 650 },
      { item: 'Mixed Thukpa', price: 700 },
    ],
  },
  {
    key: 'chowmein',
    label: 'Chowmein',
    servingType: 'single',
    items: [
      { item: 'Plain Chowmein', price: 400 },
      { item: 'Cheese Chowmein', price: 500 },
      { item: 'Veg Chowmein', price: 450 },
      { item: 'Egg Chowmein', price: 500 },
      { item: 'Mushroom Chowmein', price: 450 },
      { item: 'Veg Cheese Chowmein', price: 600 },
      { item: 'Veg Egg Chowmein', price: 650 },
      { item: 'Egg Cheese Chowmein', price: 600 },
      { item: 'Mushroom Cheese Chowmein', price: 600 },
      { item: 'Mixed Chowmein', price: 650 },
    ],
  },
  {
    key: 'spring-roll',
    label: 'Spring Roll',
    servingType: 'single',
    items: [
      { item: 'Veg Spring Roll', price: 600 },
      { item: 'Potato Spring Roll', price: 500 },
      { item: 'Egg Spring Roll', price: 650 },
      { item: 'Potato Cheese Spring Roll', price: 550 },
      { item: 'Mushroom Cheese Veg Spring Roll', price: 650 },
      { item: 'Mixed Spring Roll', price: 700 },
    ],
  },
  {
    key: 'macaroni',
    label: 'Macaroni',
    servingType: 'single',
    items: [
      { item: 'Plain Macaroni', price: 400 },
      { item: 'Cheese Macaroni', price: 500 },
      { item: 'Veg Macaroni', price: 450 },
      { item: 'Egg Macaroni', price: 500 },
      { item: 'Veg Cheese Macaroni', price: 600 },
      { item: 'Veg Egg Macaroni', price: 550 },
      { item: 'Egg Cheese Macaroni', price: 650 },
      { item: 'Mushroom Macaroni', price: 500 },
      { item: 'Veg Mushroom Macaroni', price: 550 },
      { item: 'Egg Mushroom Macaroni', price: 600 },
      { item: 'Cheese Mushroom Macaroni', price: 650 },
      { item: 'Mixed Macaroni', price: 700 },
    ],
  },
  {
    key: 'spaghetti',
    label: 'Spaghetti',
    servingType: 'single',
    items: [
      { item: 'Tomato Sauce + Cheese Spaghetti', price: 600 },
      { item: 'Mushroom Tomato Sauce + Cheese Spaghetti', price: 700 },
      { item: 'Tuna Tomato Sauce + Cheese Spaghetti', price: 750 },
      { item: 'Egg Tomato Sauce + Cheese Spaghetti', price: 700 },
      { item: 'Veg Tomato Sauce + Cheese Spaghetti', price: 700 },
      { item: 'Veg Egg Tomato Sauce + Cheese Spaghetti', price: 750 },
      { item: 'Veg Tuna Tomato Sauce + Cheese Spaghetti', price: 800 },
      { item: 'Egg Tuna Tomato Sauce + Cheese Spaghetti', price: 800 },
      { item: 'Mushroom Tuna Tomato Sauce + Cheese Spaghetti', price: 800 },
      { item: 'Mushroom Egg Tomato Sauce + Cheese Spaghetti', price: 750 },
      { item: 'Mushroom Veg Tomato Sauce + Cheese Spaghetti', price: 750 },
      { item: 'Mixed Tomato Sauce + Cheese Spaghetti', price: 850 },
    ],
  },
  {
    key: 'potatoes',
    label: 'Potatoes',
    servingType: 'single',
    items: [
      { item: 'Boiled Potato', price: 400 },
      { item: 'Veg Fried Potato', price: 550 },
      { item: 'Plain Fried Potato', price: 450 },
      { item: 'Cheese Fried Potato', price: 600 },
      { item: 'Mushroom Fried Potato', price: 550 },
      { item: 'Fried Potato with Single Omelette', price: 550 },
      { item: 'Fried Potato with Veg Cheese', price: 600 },
      { item: 'Fried Potato with Mushroom Cheese', price: 600 },
      { item: 'Fried Potato with Veg Mushroom', price: 550 },
      { item: 'Mixed Fried Potato', price: 700 },
      { item: 'Mash Potato', price: 500 },
      { item: 'Potato Chips / French Fry', price: 650 },
    ],
  },
  {
    key: 'momo',
    label: 'Mo:Mo',
    servingType: 'momo',
    items: [
      { item: 'Veg Momo', fried: 550, steam: 500 },
      { item: 'Potato Momo', fried: 550, steam: 500 },
      { item: 'Veg Cheese Momo', fried: 650, steam: 600 },
      { item: 'Potato Cheese Momo', fried: 650, steam: 600 },
      { item: 'Mixed Momo', fried: 750, steam: 700 },
    ],
  },
  {
    key: 'dessert',
    label: 'Dessert',
    servingType: 'single',
    items: [
      { item: 'Apple Pie', price: 600 },
      { item: 'Rice Pudding', price: 550 },
      { item: 'Chocolate', price: 600 },
      { item: 'Apple Fritter', price: 600 },
      { item: 'Apple Cheese Pie', price: 680 },
      { item: 'Chocolate Apple Fritter', price: 650 },
      { item: 'Snickers / Mars Momo', price: 600 },
    ],
  },
  {
    key: 'dal-bhat',
    label: 'Dal Bhat',
    servingType: 'single',
    items: [
      { item: 'Dal Bhat Set', price: 650 },
      { item: 'Plain Rice', price: 300 },
      { item: 'Dal Bhat with Single Fried Egg', price: 780 },
      { item: 'Dal Bhat with Single Omelette', price: 750 },
      { item: 'Vegetable Curry Rice', price: 600 },
    ],
  },
  {
    key: 'fried-rice',
    label: 'Fried Rice',
    servingType: 'friedrice',
    items: [
      { item: 'Plain Fried Rice', price: 400, withCheese: 500 },
      { item: 'Veg Fried Rice', price: 500, withCheese: 550 },
      { item: 'Mushroom Fried Rice', price: 500, withCheese: 550 },
      { item: 'Egg Fried Rice', price: 500, withCheese: 550 },
      { item: 'Veg Mushroom Fried Rice', price: 550, withCheese: 600 },
      { item: 'Veg Egg Fried Rice', price: 600, withCheese: 650 },
      { item: 'Mushroom Egg Fried Rice', price: 600, withCheese: 650 },
      { item: 'Mixed Fried Rice', price: 650, withCheese: 700 },
    ],
  },
  {
    key: 'hard-drinks',
    label: 'Hard Drinks',
    servingType: 'single',
    items: [
      { item: 'Tuborg Beer', price: 750 },
      { item: 'Everest Beer', price: 700 },
      { item: 'Khukuri Rum', price: 800 },
      { item: 'Tuborg Can Beer', price: 600 },
    ],
  },
];
