import { Trek } from '@/types/trek';

export enum TrekIdEnum {
  ABC_TREK = 'abc-trek',
  EBC_TREK = 'ebc-trek',
  GHOREPANI_POON_HILL_TREK = 'ghorepani-poon-hill-trek',
  GOKYO_VALLEY_TREK = 'gokyo-valley-trek',
  LANGTANG_VALLEY = 'langtang-valley',
  MANASLU_CIRCUIT = 'manaslu-circuit',
  MARDI_HIMAL_TREK = 'mardi-himal-trek',
}

export const TREKS: Trek[] = [
  {
    id: 'ebc-trek',
    title: 'EBC Trek',
    region: 'Khumbu Valley',
    description:
      "Trek to the base of the world's highest peak through the legendary Khumbu Valley. Pass through iconic Sherpa villages like Namche Bazaar and Tengboche, cross glacial moraines, and stand before the 5,364m marker surrounded by the world's greatest Himalayan giants.",
    difficulty: 'Challenging',
    duration: '14 Days',
    altitude: '5,364m',
    season: 'Mar-May, Sept-Nov',
    price: 30000,
    imageUrl: '/images/ebc.jpg',
    isPopular: true,
    keywords: ['everest base camp', 'ebc', 'khumbu', 'everest'],
  },
  {
    id: 'manaslu-circuit',
    title: 'Manaslu Circuit Trek',
    region: 'Manaslu Region',
    description:
      "A remote and rugged circuit around Manaslu, the world's eighth highest mountain, offering raw Himalayan wilderness far from the crowds. Cross the Larkya La Pass at 5,106m, traverse ancient Tibetan-influenced villages, and experience Nepal's most dramatic restricted-area trek.",
    difficulty: 'Challenging',
    duration: '14-18 Days',
    altitude: '5,106m',
    season: 'Mar-May, Sept-Nov',
    price: 20000,
    imageUrl: '/images/erik-OwJ6Cn_DnHM-unsplash.jpg',
    isPopular: true,
    keywords: ['manaslu', 'circuit', 'manaslu circuit'],
  },
  {
    id: 'langtang-valley',
    title: 'Langtang Valley Trek',
    region: 'Langtang Region',
    description:
      'A culturally rich journey through lush rhododendron forests and traditional Tamang villages into the breathtaking Langtang Valley. Enjoy close-up views of glaciers and snow-capped peaks, and visit the ancient Kyanjin Gompa monastery nestled beneath the ice.',
    difficulty: 'Moderate',
    duration: '7-10 Days',
    altitude: '4,773m',
    season: 'Mar-May, Sep-Dec',
    price: 10000,
    imageUrl: '/images/redmaz-pham-yQnfR9N67OQ-unsplash.jpg',
    isPopular: true,
    keywords: ['langtang', 'langtang valley'],
  },
  {
    id: 'abc-trek',
    title: 'Annapurna Base Camp Trek',
    region: 'Annapurna Region',
    description:
      'A breathtaking trek through terraced fields, rhododendron forests, and Gurung villages, leading to the heart of the Annapurna Sanctuary surrounded by towering Himalayan peaks.',
    difficulty: 'Challenging',
    duration: '7-10 Days',
    altitude: '4,130m',
    season: 'Mar-May, Sep-Nov',
    price: 12000,
    imageUrl: '/images/abc/annapurna.jpg',
    isPopular: false,
    keywords: [
      'annapurna',
      'annapurna base camp',
      'abc',
      'annapurna sanctuary',
    ],
  },

  {
    id: 'gokyo-valley-trek',
    title: 'Gokyo Valley Trek',
    region: 'Khumbu Region',
    description:
      "The quieter alternative glacial lakes, Nepal's longest glacier, and four 8,000m peaks from a single summit.",
    difficulty: 'Challenging',
    duration: '13-14 Days',
    altitude: '5,357m',
    season: 'Mar-May, Sept-Nov',
    price: 12000,
    imageUrl: '/images/gokyo/gokyo.webp',
    isPopular: false,
    keywords: ['gokyo valley', 'gokyo', 'gok', 'valley'],
  },
  {
    id: 'ghorepani-poon-hill-trek',
    title: 'Ghorepani Poon Hill Trek',
    region: 'Annapurna Region',
    description:
      'Beginner-friendly on paper, genuinely jaw-dropping in practice."',
    difficulty: 'Moderate',
    duration: '5-7 Days',
    altitude: '3,210m',
    season: 'Mar-May, Sept-Nov',
    price: 12000,
    imageUrl: '/images/poonhill/poonhill.webp',
    isPopular: false,
    keywords: ['ghorepani poon hill trek', 'poonhill', 'ghorepani', 'poon'],
  },
  {
    id: 'mardi-himal-trek',
    title: 'Mardi Himal Trek',
    region: 'Annapurna Region',
    description:
      "Intimate, uncrowded, and closer to Machapuchare's perfect pyramid than any other trail in the Annapurna region.",
    difficulty: 'Moderate',
    duration: '6-7 Days',
    altitude: '4,500m',
    season: 'Mar-May, Sep-Dec',
    price: 12000,
    imageUrl: '/images/mardi/mardi.webp',
    isPopular: false,
    keywords: ['mardi himal trek', 'mardi'],
  },
  {
    id: 'shey-phoksundo',
    title: 'Shey Phoksundo Trek',
    region: 'Dolpo Region',
    description:
      'A remote Himalayan journey into Dolpo’s stark, cinematic wilderness leading to the surreal turquoise waters of Shey Phoksundo Lake, framed by cliffs, ancient villages, and untouched Tibetan-Bon culture.',
    difficulty: 'Moderate',
    duration: '10-12 Days',
    altitude: '3,611m',
    season: 'Apr-Jun, Sep-Nov',
    price: 18000,
    imageUrl: '/images/shey/shey.webp',
    isPopular: false,
    keywords: ['shey phoksundo trek', 'dolpo trek', 'phoksundo lake trek'],
  },
];

export const POPULAR_TREKS = TREKS.filter((trek) => trek.isPopular);
