import { Trek } from '@/types/trek';

export enum TrekIdEnum {
  ABC_TREK = 'abc-trek',
  EBC_TREK = 'ebc-trek',
  GHOREPANI_POON_HILL_TREK = 'ghorepani-poon-hill-trek',
  GOKYO_VALLEY_TREK = 'gokyo-valley-trek',
  LANGTANG_VALLEY = 'langtang-valley',
  MANASLU_CIRCUIT = 'manaslu-circuit',
  MARDI_HIMAL_TREK = 'mardi-himal-trek',
}

export const TREKS: Trek[] = [
  {
    id: 'ebc-trek',
    title: 'EBC Trek',
    region: 'Khumbu Valley',
    description:
      'Trek through the Khumbu region, passing Sherpa villages, monasteries, glaciers, and high Himalayan landscapes on the way to Everest Base Camp.',
    difficulty: 'Challenging',
    duration: '12 Days',
    altitude: '5,545m',
    season: 'Mar-May, Sep-Nov',
    price: 30000,
    imageUrl: '/images/ebc.jpg',
    isPopular: true,
    keywords: ['everest base camp', 'ebc', 'khumbu', 'everest'],
  },
  {
    id: 'manaslu-circuit',
    title: 'Manaslu Circuit Trek',
    region: 'Manaslu Region',
    description:
      "Circle the world's eighth-highest mountain through the Budhi Gandaki Valley, upper Nubri settlements, and high alpine terrain before crossing the 5,106 m Larkya La Pass.",
    difficulty: 'Challenging',
    duration: '13 Days',
    altitude: '5,106m',
    season: 'Mar-May, Sep-Nov',
    price: 20000,
    imageUrl: '/images/erik-OwJ6Cn_DnHM-unsplash.jpg',
    isPopular: true,
    keywords: ['manaslu', 'circuit', 'manaslu circuit'],
  },
  {
    id: 'langtang-valley',
    title: 'Langtang Valley Trek',
    region: 'Langtang Region',
    description:
      'Follow the Langtang Khola from forested valleys and Tamang villages into the alpine landscape of Kyanjin Gompa, with a climb to Kyanjin Ri at 4,773 m.',
    difficulty: 'Moderate',
    duration: '7 Days',
    altitude: '4,773m',
    season: 'Mar-May, Oct-Nov',
    price: 10000,
    imageUrl: '/images/redmaz-pham-yQnfR9N67OQ-unsplash.jpg',
    isPopular: true,
    keywords: ['langtang', 'langtang valley'],
  },
  {
    id: 'abc-trek',
    title: 'Annapurna Base Camp Trek',
    region: 'Annapurna Region',
    description:
      'A breathtaking trek through terraced fields, rhododendron forests, and Gurung villages, leading to the heart of the Annapurna Sanctuary surrounded by towering Himalayan peaks.',
    difficulty: 'Moderate',
    duration: '7 Days',
    altitude: '4,130m',
    season: 'Mar-May, Sep-Nov',
    price: 12000,
    imageUrl: '/images/abc/annapurna.jpg',
    isPopular: false,
    keywords: [
      'annapurna',
      'annapurna base camp',
      'abc',
      'annapurna sanctuary',
    ],
  },

  {
    id: 'gokyo-valley-trek',
    title: 'Gokyo Valley Trek',
    region: 'Khumbu Region',
    description:
      "The quieter alternative glacial lakes, Nepal's longest glacier, and four 8,000m peaks from a single summit.",
    difficulty: 'Challenging',
    duration: '11 Days',
    altitude: '5,357m',
    season: 'Mar-May, Sep-Nov',
    price: 12000,
    imageUrl: '/images/gokyo/gokyo.webp',
    isPopular: false,
    keywords: ['gokyo valley', 'gokyo', 'gok', 'valley'],
  },
  {
    id: 'ghorepani-poon-hill-trek',
    title: 'Ghorepani Poon Hill Trek',
    region: 'Annapurna Region',
    description:
      'Beginner-friendly on paper, genuinely jaw-dropping in practice."',
    difficulty: 'Moderate',
    duration: '5 Days',
    altitude: '3,210m',
    season: 'Mar-May, Sep-Nov',
    price: 12000,
    imageUrl: '/images/poonhill/poonhill.webp',
    isPopular: false,
    keywords: ['ghorepani poon hill trek', 'poonhill', 'ghorepani', 'poon'],
  },
  {
    id: 'mardi-himal-trek',
    title: 'Mardi Himal Trek',
    region: 'Annapurna Region',
    description:
      "Intimate, uncrowded, and closer to Machapuchare's perfect pyramid than any other trail in the Annapurna region.",
    difficulty: 'Moderate',
    duration: '5 Days',
    altitude: '4,500m',
    season: 'Mar-May, Sep-Nov',
    price: 12000,
    imageUrl: '/images/mardi/mardi.webp',
    isPopular: false,
    keywords: ['mardi himal trek', 'mardi'],
  },
  {
    id: 'shey-phoksundo',
    title: 'Shey Phoksundo Trek',
    region: 'Dolpo Region',
    description:
      'A remote Himalayan journey into Dolpo’s stark, cinematic wilderness leading to the surreal turquoise waters of Shey Phoksundo Lake, framed by cliffs, ancient villages, and untouched Tibetan-Bon culture.',
    difficulty: 'Moderate',
    duration: '8 Days',
    altitude: '3,660m',
    season: 'March-May, Sep-Nov',
    price: 18000,
    imageUrl: '/images/shey/shey.webp',
    isPopular: false,
    keywords: ['shey phoksundo trek', 'dolpo trek', 'phoksundo lake trek'],
  },
  {
    id: 'tilicho-lake-trek',
    title: 'Tilicho Lake Trek',
    region: 'Annapurna Region',
    description:
      'A dramatic high-altitude adventure through the arid valleys of Manang to the turquoise waters of Tilicho Lake, combined with the legendary crossing of Thorong La Pass beneath the towering Annapurna massif.',
    difficulty: 'Challenging',
    duration: '11 Days',
    altitude: '4,919m',
    season: 'Mar-May, Sep-Nov',
    price: 22000,
    imageUrl: '/images/tilicho/tilicho.webp',
    isPopular: false,
    keywords: [
      'tilicho lake trek',
      'thorong la pass trek',
      'annapurna circuit tilicho',
      'tilicho trek',
      'manang trek',
    ],
  },
];

export const POPULAR_TREKS = TREKS.filter((trek) => trek.isPopular);
